# Generated by Django 4.1.7 on 2023-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
