# Generated by Django 4.1.7 on 2023-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
