# Generated by Django 4.1.7 on 2023-04-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_alter_field_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('name', 'farm')},
        ),
    ]
