# Generated by Django 4.1.7 on 2023-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_alter_field_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
