# Generated by Django 4.1.7 on 2023-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_alter_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='coordinates',
            field=models.CharField(max_length=500),
        ),
    ]
