# Generated by Django 4.1.7 on 2023-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='farmers', to='user.user'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='country',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
