# Generated by Django 4.1.7 on 2023-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_role'),
        ('farm', '0002_farm_farmers_alter_farm_country_alter_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='fieldmanagers',
            field=models.ManyToManyField(blank=True, related_name='fieldmanagers', to='user.user'),
        ),
    ]
